### ISSUE TITLE
HOW TO INSTALL

### ISSUE THREAD

**Issue by cdfmlr** [innovationOUtside/flowchart_js_jp_proxy_widget#3]
I love this magic idea. It's really useful and thanks to share it on cdfmlr/pyflowchart#8.

However, I have spent minutes to figure out how to install this. As what I'm posted on https://github.com/cdfmlr/pyflowchart/issues/8#issuecomment-862475557, here are my steps:

1. install `jp_proxy_widget`

```sh
$ pip install jp_proxy_widget
$ jupyter nbextension install --py --symlink --sys-prefix jp_proxy_widget
$ jupyter nbextension enable --py --sys-prefix jp_proxy_widget
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
$ jupyter labextension install jp_proxy_widget
```

2. install `jp_flowchartjs`

```sh
$ pip install jp_flowchartjs
```

3. install `pyflowchart`

```sh
pip3 install pyflowchart
```

4. Run `jupyter lab`, open a notebook, and run this:

```sh
from jp_flowchartjs.jp_flowchartjs import *
from IPython.core.magic import register_cell_magic
from pyflowchart import Flowchart

@register_cell_magic
def flowchart_magic(line, cell):
    "Send code to simulator."
    return FlowchartWidget().charter(cell, embed=True)
    
    
@register_cell_magic
def pyflowchart_magic(line, cell):
    "Generate flowchart code and send to flow charter."
    fc = Flowchart.from_code(cell)
    return FlowchartWidget().charter(str(fc.flowchart()), embed=True)
```

5. then, enjoy the magic:

```python
%%flowchart_magic
st=>start: Start
e=>end: End
op1=>operation: Generate
op2=>parallel: Evaluate
st(right)->op1(right)->op2
op2(path1, top)->op1
op2(path2, right)->e
```

&

```python
%%pyflowchart_magic 
import time

def demo(msg='demo'):
    for i in range(10):
        print(f'{msg} loopcount is {i}')
        time.sleep(i)
```

Why not put these steps (or else docs alternatively) into the README, to help people to setup this magic.

**Comment by cdfmlr** [comment]
btw, is there any idea to simply this flow? I guess  there should be ways to avoid manually copy and paste these `register_cell_magic` every time you want to use `%%flowchart_magic` and `%%pyflowchart_magic`.

**Comment by psychemedia** [comment]
Hi, thanks for the prompt, I just pushed an update. You should now able to just pip install the package from Github and then run `%load_ext jp_flowchartjs` to get the magics into a notebook.

The `jp_proxy_widget` may be overkill; I was using it as a quick way to load the `flowchart.js` code into the notebook and simplify passing the code in the magic cell to it. There may be simpler/cleaner ways, like creating a custom ipywidget, perhaps.
